trigger:
- master

pool: az400m05l05a-pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo "Run install"
    npm install
    echo "Run build"
    npm run build
    echo "Run Test"
    npm test
  displayName: 'npm install, build, and test'
