trigger:
- master

pool: az400m05l05a-pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: node -v
  displayName: "check node version"

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'

- script: npm test
  displayName: 'npm test'
