trigger:
- master

pool: home-pool

steps:
- script: npm -v
  displayName: "check node version"

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'
