trigger:
- master

pool: az400m05l05a-pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
- script: npm run build
- script: npm test
